# Generated by Django 3.2.7 on 2021-09-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(default='NULL', max_length=100, verbose_name='name')),
                ('year', models.CharField(default='NULL', max_length=5)),
                ('rating', models.CharField(default='NULL', max_length=5)),
                ('description', models.CharField(default='NULL', max_length=1500)),
                ('video_link', models.CharField(default='NULL', max_length=200, verbose_name='video link')),
                ('video_cotent', models.FileField(default='NULL', upload_to='videos/', verbose_name='video')),
                ('trailer_link', models.CharField(default='NULL', max_length=200, verbose_name='trailer link')),
                ('trailer_cotent', models.FileField(default='NULL', upload_to='videos/', verbose_name='trailer')),
                ('photo', models.CharField(default='NULL', max_length=100)),
                ('watches24h', models.IntegerField(default=0)),
                ('watches7d', models.IntegerField(default=0)),
                ('watches1m', models.IntegerField(default=0)),
                ('watches_all', models.IntegerField(default=0, verbose_name='watches all')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('comments_counter', models.IntegerField(default=0, verbose_name='comments counter')),
                ('director', models.ManyToManyField(blank=True, to='BotShell.Director')),
            ],
            options={
                'verbose_name': 'film',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(default='NULL', max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=50, verbose_name='name')),
                ('favourite', models.ManyToManyField(blank=True, to='BotShell.Films')),
                ('requests', models.ManyToManyField(blank=True, to='BotShell.Requests')),
            ],
        ),
        migrations.AddField(
            model_name='films',
            name='genres',
            field=models.ManyToManyField(blank=True, to='BotShell.Genres'),
        ),
        migrations.AddField(
            model_name='films',
            name='stars',
            field=models.ManyToManyField(blank=True, to='BotShell.Stars'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='NULL', max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotShell.users')),
                ('film_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BotShell.films')),
            ],
        ),
    ]
