# Generated by Django 3.2.7 on 2021-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='trailer_cotent',
            new_name='trailer_file',
        ),
        migrations.RenameField(
            model_name='films',
            old_name='video_cotent',
            new_name='video_file',
        ),
        migrations.AddField(
            model_name='users',
            name='history',
            field=models.ManyToManyField(blank=True, to='BotShell.Films'),
        ),
        migrations.AddField(
            model_name='users',
            name='id_dislikes',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='id dislikes'),
        ),
        migrations.AddField(
            model_name='users',
            name='id_likes',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='id likes'),
        ),
        migrations.AddField(
            model_name='users',
            name='id_tele',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='paper_count',
            field=models.IntegerField(default=5, verbose_name='paper count'),
        ),
        migrations.AddField(
            model_name='users',
            name='search_way',
            field=models.CharField(blank=True, choices=[('by_name', 'by name'), ('by_actor', 'by actor'), ('by_director', 'by director'), ('by_all', 'by all')], max_length=15, verbose_name='search way'),
        ),
        migrations.AlterField(
            model_name='users',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='NULL', to='BotShell.Films'),
        ),
        migrations.AlterField(
            model_name='users',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='NULL', to='BotShell.Requests'),
        ),
    ]
