# Generated by Django 3.2.7 on 2021-09-05 16:12

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0002_auto_20210905_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', djrichtextfield.models.RichTextField(max_length=1024)),
            ],
        ),
    ]
