# Generated by Django 3.2.7 on 2021-09-05 16:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=1024),
        ),
    ]
