# Generated by Django 3.2.7 on 2021-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0004_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
