# Generated by Django 3.2.7 on 2021-09-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0005_message_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
