# Generated by Django 3.2.7 on 2021-09-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0006_alter_films_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(default=0, verbose_name='admin tg id')),
            ],
        ),
    ]
