# Generated by Django 3.2.7 on 2021-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0007_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='genres',
            field=models.ManyToManyField(to='BotShell.Genres'),
        ),
    ]
