# Generated by Django 3.2.7 on 2021-09-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0008_alter_films_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='genres',
            field=models.ManyToManyField(blank=True, to='BotShell.Genres'),
        ),
    ]
