# Generated by Django 3.2.7 on 2021-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0009_alter_films_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='film_name',
            field=models.CharField(default='NULL', max_length=100, unique=True, verbose_name='name'),
        ),
    ]
