# Generated by Django 3.2.7 on 2021-09-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0013_trendingfilms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='search_way',
            field=models.CharField(choices=[('by_name', 'by name'), ('by_actor', 'by actor'), ('by_director', 'by director'), ('by_all', 'by all')], default='by name', max_length=15, verbose_name='search way'),
        ),
    ]
