# Generated by Django 3.2.7 on 2021-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0014_alter_users_search_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_dislikes',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id_likes',
        ),
        migrations.AddField(
            model_name='users',
            name='disliked_films',
            field=models.ManyToManyField(blank=True, related_name='NULL5', to='BotShell.Films'),
        ),
        migrations.AddField(
            model_name='users',
            name='liked_films',
            field=models.ManyToManyField(blank=True, related_name='NULL4', to='BotShell.Films'),
        ),
        migrations.AlterField(
            model_name='users',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='NULL2', to='BotShell.Films'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='NULL1', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='NULL3', to='BotShell.Requests'),
        ),
    ]
