# Generated by Django 3.2.7 on 2021-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0015_auto_20210911_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='name_NULL1', max_length=50, verbose_name='name'),
        ),
    ]
