# Generated by Django 3.2.7 on 2021-09-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0016_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='photo',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
