# Generated by Django 3.2.7 on 2021-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0018_lastsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='search_way',
            field=models.CharField(choices=[('by name', 'by name'), ('by actor', 'by actor'), ('by director', 'by director'), ('by all', 'by all')], default='by name', max_length=15, verbose_name='search way'),
        ),
    ]
