# Generated by Django 3.2.7 on 2021-09-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0019_alter_users_search_way'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='name',
            new_name='film_name',
        ),
        migrations.AddField(
            model_name='requests',
            name='id_tele',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='requests',
            name='verification_process',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=3),
        ),
    ]
