# Generated by Django 3.2.7 on 2021-09-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0020_auto_20210926_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='verification_process',
            field=models.CharField(choices=[('🔄', '🔄'), ('✅', '✅'), ('⛔️', '⛔️')], default='🔄', max_length=2),
        ),
    ]
