# Generated by Django 3.2.7 on 2021-09-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0021_alter_requests_verification_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admins',
            options={'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='directors',
            options={'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='generalhistory',
            options={'verbose_name': 'General History', 'verbose_name_plural': 'General History'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='lastsearch',
            options={'verbose_name': 'Last search films', 'verbose_name_plural': 'Last search films'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='stars',
            options={'verbose_name': 'Star', 'verbose_name_plural': 'Stars'},
        ),
        migrations.AlterModelOptions(
            name='trendingfilms',
            options={'verbose_name': 'Trending Film', 'verbose_name_plural': 'Trending Films'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
