# Generated by Django 3.2.7 on 2021-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotShell', '0022_auto_20210927_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='similar_films',
            field=models.ManyToManyField(blank=True, related_name='_BotShell_films_similar_films_+', to='BotShell.Films'),
        ),
    ]
